using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MoneyMirror.Core.Models
{
    /// <summary>
    /// Represents personalized financial advice generated by AI for a specific child.
    /// Advice is tailored based on recent spending patterns, mood trends, and personality type.
    /// Generated weekly or triggered by specific events (overspending, goal progress, etc.)
    /// Displayed in child and parent dashboards as actionable tips.
    /// </summary>
    public class Advice
    {
        /// <summary>
        /// Primary key for the Advice entity
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int AdviceID { get; set; }

        /// <summary>
        /// Target audience for this advice.
        /// Values: "Parent" or "Child"
        /// Determines tone and complexity of advice content.
        /// </summary>
        [Required]
        [MaxLength(20)]
        public string TargetType { get; set; }

        /// <summary>
        /// Short title/category for the advice.
        /// Example: "Spending Tip", "Savings Reminder", "Mood Alert"
        /// Helps organize advice into categories in the UI.
        /// </summary>
        [Required]
        [MaxLength(200)]
        public string Title { get; set; }

        /// <summary>
        /// The actual advice content/text.
        /// Should be personalized, actionable, and encouraging.
        /// Example for child: "You spent 80% on toys this week - try saving 20% next time! 🎯"
        /// Example for parent: "Emma's impulse purchases increased this week. Consider setting a 24-hour waiting rule."
        /// </summary>
        [Required]
        [MaxLength(2000)]
        public string Content { get; set; }

        /// <summary>
        /// Timestamp when this advice was generated by the AI system
        /// </summary>
        [Required]
        public DateTime GeneratedDate { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Event or condition that triggered this advice generation.
        /// Values: "WeeklyAnalysis", "OverspendingDetected", "GoalProgressLow", 
        ///         "MoodPattern", "PersonalityUpdate"
        /// Helps track which AI triggers are most effective.
        /// </summary>
        [Required]
        [MaxLength(100)]
        public string SourceTrigger { get; set; }

        /// <summary>
        /// Indicates whether the user (parent or child) has read/acknowledged this advice.
        /// False = unread, True = read
        /// Used to highlight new advice in the UI.
        /// </summary>
        [Required]
        public bool IsRead { get; set; } = false;

        /// <summary>
        /// Optional expiration date for time-sensitive advice.
        /// After this date, advice may be archived or hidden from active feed.
        /// Example: Advice about last week's spending expires after 7 days.
        /// Null if advice doesn't expire.
        /// </summary>
        public DateTime? ExpiresAt { get; set; }

        /// <summary>
        /// Foreign key to Child table.
        /// The child this advice is about/for.
        /// </summary>
        [Required]
        public int ChildID { get; set; }

        // ==================== NAVIGATION PROPERTIES ====================

        /// <summary>
        /// Reference to the child this advice is about
        /// </summary>
        [ForeignKey("ChildID")]
        public virtual Child Child { get; set; }
    }
}
