// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyMirror.Infrastructure.Data;

#nullable disable

namespace MoneyMirror.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260524195646_Update-QuizTemplate")]
    partial class UpdateQuizTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoneyMirror.Core.Models.AchievementType", b =>
                {
                    b.Property<int>("AchievementTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementTypeID"));

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IconURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AchievementTypeID");

                    b.ToTable("AchievementTypes");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Advice", b =>
                {
                    b.Property<int>("AdviceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdviceID"));

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GeneratedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SourceTrigger")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AdviceID");

                    b.HasIndex("ChildID", "IsRead")
                        .HasDatabaseName("IX_Advice_Child_IsRead");

                    b.ToTable("Advices");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Allowance", b =>
                {
                    b.Property<int>("AllowanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllowanceID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.Property<int?>("DailyHour")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GivenDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCreditedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MonthlyDay")
                        .HasColumnType("int");

                    b.Property<int>("ParentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SetDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WeeklyDay")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AllowanceID");

                    b.HasIndex("ParentID");

                    b.HasIndex("ChildID", "SetDate")
                        .HasDatabaseName("IX_Allowance_Child_SetDate");

                    b.ToTable("Allowances");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Character", b =>
                {
                    b.Property<int>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterID"));

                    b.Property<string>("DefaultImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CharacterID");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Character_Name_Unique");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.CharacterState", b =>
                {
                    b.Property<int>("StateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateID"));

                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ScreenContext")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StateID");

                    b.HasIndex("CharacterID", "ScreenContext")
                        .IsUnique()
                        .HasDatabaseName("IX_CharacterState_Character_Screen_Unique");

                    b.ToTable("CharacterStates");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Child", b =>
                {
                    b.Property<int>("ChildID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChildID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("CurrentBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsPersonalityFinalized")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoginCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TypeID")
                        .HasColumnType("int");

                    b.HasKey("ChildID");

                    b.HasIndex("CharacterID");

                    b.HasIndex("LoginCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Child_LoginCode_Unique");

                    b.HasIndex("TypeID");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.ChildAchievement", b =>
                {
                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.Property<int>("AchievementTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EarnedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("ChildID", "AchievementTypeID");

                    b.HasIndex("AchievementTypeID");

                    b.ToTable("ChildAchievements");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("MoneyAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MoodID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ExpenseID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("LogDate")
                        .HasDatabaseName("IX_Expense_LogDate");

                    b.HasIndex("MoodID");

                    b.HasIndex("ChildID", "LogDate")
                        .HasDatabaseName("IX_Expense_Child_LogDate");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.ExpenseCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryID");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.InitialProfilingQuestionnaire", b =>
                {
                    b.Property<int>("QuestionnaireID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionnaireID"));

                    b.Property<int?>("CalculatedTypeID")
                        .HasColumnType("int");

                    b.Property<int>("ChildAgeGroup")
                        .HasColumnType("int");

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FeelingAfterSpending")
                        .HasColumnType("int");

                    b.Property<int>("FeelingWhenSavingGrows")
                        .HasColumnType("int");

                    b.Property<int>("HasAllowance")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MoneyMindset")
                        .HasColumnType("int");

                    b.Property<int>("OutOfMoneyBehavior")
                        .HasColumnType("int");

                    b.Property<int>("ReactionTo100")
                        .HasColumnType("int");

                    b.Property<string>("SpendingCategories")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int>("SpendingPace")
                        .HasColumnType("int");

                    b.Property<int>("TriesToSave")
                        .HasColumnType("int");

                    b.HasKey("QuestionnaireID");

                    b.HasIndex("CalculatedTypeID");

                    b.HasIndex("ChildID")
                        .IsUnique()
                        .HasDatabaseName("IX_InitialProfiling_ChildID_Unique");

                    b.ToTable("InitialProfilingQuestionnaires");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Mood", b =>
                {
                    b.Property<int>("MoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoodID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MoodID");

                    b.ToTable("Moods");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<int?>("ChildID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NotificationID");

                    b.HasIndex("ChildID", "IsRead")
                        .HasDatabaseName("IX_Notification_Child_IsRead")
                        .HasFilter("[ChildID] IS NOT NULL");

                    b.HasIndex("ParentID", "IsRead")
                        .HasDatabaseName("IX_Notification_Parent_IsRead")
                        .HasFilter("[ParentID] IS NOT NULL");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Parent", b =>
                {
                    b.Property<int>("ParentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParentID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmailChangeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailChangeCodeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailConfirmationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailConfirmationCodeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPermanentlyDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetCodeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PermanentDeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("ParentID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Parent_Email_Unique");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.ParentChild", b =>
                {
                    b.Property<int>("ParentID")
                        .HasColumnType("int");

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.HasKey("ParentID", "ChildID");

                    b.HasIndex("ChildID");

                    b.ToTable("ParentChildren");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.PersonalityType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeID"));

                    b.Property<string>("ChildName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FunFacts")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StaticRecommendation")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Traits")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("TypeID");

                    b.ToTable("PersonalityTypes");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.QuizAnswer", b =>
                {
                    b.Property<int>("AnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerID"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FeedbackMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PersonalityTypeID")
                        .HasColumnType("int");

                    b.Property<int>("StoryID")
                        .HasColumnType("int");

                    b.HasKey("AnswerID");

                    b.HasIndex("PersonalityTypeID");

                    b.HasIndex("StoryID");

                    b.ToTable("QuizAnswers");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.QuizLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<int>("AnswerID")
                        .HasColumnType("int");

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("PersonalityTypeTypeID")
                        .HasColumnType("int");

                    b.Property<int>("StoryID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("AnswerID");

                    b.HasIndex("PersonalityTypeTypeID");

                    b.HasIndex("StoryID");

                    b.HasIndex("ChildID", "CompletedDate")
                        .HasDatabaseName("IX_QuizLog_Child_CompletedDate");

                    b.HasIndex("ChildID", "StoryID")
                        .IsUnique()
                        .HasDatabaseName("IX_QuizLog_Child_Story_Unique");

                    b.ToTable("QuizLogs");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.SavingsGoal", b =>
                {
                    b.Property<int>("GoalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoalID"));

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsChallenge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<decimal?>("RewardValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("GoalID");

                    b.HasIndex("ParentID");

                    b.HasIndex("ChildID", "Status")
                        .HasDatabaseName("IX_SavingsGoal_Child_Status");

                    b.ToTable("SavingsGoals");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.StoryQuizTemplate", b =>
                {
                    b.Property<int>("StoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoryID"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TargetAgeMax")
                        .HasColumnType("int");

                    b.Property<int>("TargetAgeMin")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("StoryID");

                    b.HasIndex("TargetAgeMin", "TargetAgeMax")
                        .HasDatabaseName("IX_StoryQuiz_AgeRange");

                    b.ToTable("StoryQuizTemplates");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<int?>("AllowanceID")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransactionID");

                    b.HasIndex("AllowanceID");

                    b.HasIndex("ParentID");

                    b.HasIndex("ChildID", "TransactionDate")
                        .HasDatabaseName("IX_Transaction_Child_TransactionDate");

                    b.HasIndex("Type", "TransactionDate")
                        .HasDatabaseName("IX_Transaction_Type_TransactionDate");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Advice", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("Advices")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Allowance", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("Allowances")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.Parent", "Parent")
                        .WithMany("Allowances")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.CharacterState", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.Character", "Character")
                        .WithMany("CharacterStates")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Child", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.Character", "SelectedCharacter")
                        .WithMany("Children")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MoneyMirror.Core.Models.PersonalityType", "PersonalityType")
                        .WithMany("Children")
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PersonalityType");

                    b.Navigation("SelectedCharacter");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.ChildAchievement", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.AchievementType", "AchievementType")
                        .WithMany("ChildAchievements")
                        .HasForeignKey("AchievementTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("ChildAchievements")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AchievementType");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Expense", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.ExpenseCategory", "ExpenseCategory")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("Expenses")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.Mood", "Mood")
                        .WithMany("Expenses")
                        .HasForeignKey("MoodID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("ExpenseCategory");

                    b.Navigation("Mood");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.InitialProfilingQuestionnaire", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.PersonalityType", "CalculatedPersonalityType")
                        .WithMany()
                        .HasForeignKey("CalculatedTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithOne("InitialProfilingQuestionnaire")
                        .HasForeignKey("MoneyMirror.Core.Models.InitialProfilingQuestionnaire", "ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalculatedPersonalityType");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Notification", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("Notifications")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoneyMirror.Core.Models.Parent", "Parent")
                        .WithMany("Notifications")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.ParentChild", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("ParentChildren")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.Parent", "Parent")
                        .WithMany("ParentChildren")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.QuizAnswer", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.PersonalityType", "PersonalityType")
                        .WithMany()
                        .HasForeignKey("PersonalityTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.StoryQuizTemplate", "StoryQuizTemplate")
                        .WithMany("Answers")
                        .HasForeignKey("StoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalityType");

                    b.Navigation("StoryQuizTemplate");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.QuizLog", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.QuizAnswer", "QuizAnswer")
                        .WithMany("QuizLogs")
                        .HasForeignKey("AnswerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("QuizLogs")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.PersonalityType", null)
                        .WithMany("QuizLogs")
                        .HasForeignKey("PersonalityTypeTypeID");

                    b.HasOne("MoneyMirror.Core.Models.StoryQuizTemplate", "StoryQuizTemplate")
                        .WithMany("QuizLogs")
                        .HasForeignKey("StoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("QuizAnswer");

                    b.Navigation("StoryQuizTemplate");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.SavingsGoal", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("SavingsGoals")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.Parent", "Parent")
                        .WithMany("ChallengeGoals")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Transaction", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.Allowance", "Allowance")
                        .WithMany("Transactions")
                        .HasForeignKey("AllowanceID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("Transactions")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.Parent", "Parent")
                        .WithMany("InitiatedTransactions")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Allowance");

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.AchievementType", b =>
                {
                    b.Navigation("ChildAchievements");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Allowance", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Character", b =>
                {
                    b.Navigation("CharacterStates");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Child", b =>
                {
                    b.Navigation("Advices");

                    b.Navigation("Allowances");

                    b.Navigation("ChildAchievements");

                    b.Navigation("Expenses");

                    b.Navigation("InitialProfilingQuestionnaire");

                    b.Navigation("Notifications");

                    b.Navigation("ParentChildren");

                    b.Navigation("QuizLogs");

                    b.Navigation("SavingsGoals");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Mood", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Parent", b =>
                {
                    b.Navigation("Allowances");

                    b.Navigation("ChallengeGoals");

                    b.Navigation("InitiatedTransactions");

                    b.Navigation("Notifications");

                    b.Navigation("ParentChildren");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.PersonalityType", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("QuizLogs");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.QuizAnswer", b =>
                {
                    b.Navigation("QuizLogs");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.StoryQuizTemplate", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("QuizLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
