// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyMirror.Infrastructure.Data;

#nullable disable

namespace MoneyMirror.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260617014531_UpdateChildAgeGroup")]
    partial class UpdateChildAgeGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoneyMirror.Core.Models.AchievementType", b =>
                {
                    b.Property<int>("AchievementTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementTypeID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Threshold")
                        .HasColumnType("int");

                    b.HasKey("AchievementTypeID");

                    b.ToTable("AchievementTypes");

                    b.HasData(
                        new
                        {
                            AchievementTypeID = 1,
                            Category = "Quiz",
                            Description = "Answered your first quiz question!",
                            IconURL = "/images/badges/first-step.png",
                            Name = "First Step",
                            Threshold = 1
                        },
                        new
                        {
                            AchievementTypeID = 2,
                            Category = "Quiz",
                            Description = "Answered 10 quiz questions.",
                            IconURL = "/images/badges/quiz-explorer.png",
                            Name = "Quiz Explorer",
                            Threshold = 10
                        },
                        new
                        {
                            AchievementTypeID = 3,
                            Category = "Quiz",
                            Description = "Answered 20 quiz questions.",
                            IconURL = "/images/badges/quiz-master.png",
                            Name = "Quiz Master",
                            Threshold = 20
                        },
                        new
                        {
                            AchievementTypeID = 4,
                            Category = "Quiz",
                            Description = "Answered 50 quiz questions!",
                            IconURL = "/images/badges/quiz-legend.png",
                            Name = "Quiz Legend",
                            Threshold = 50
                        },
                        new
                        {
                            AchievementTypeID = 5,
                            Category = "Goal",
                            Description = "Completed your first savings goal!",
                            IconURL = "/images/badges/goal-getter.png",
                            Name = "Goal Getter",
                            Threshold = 1
                        },
                        new
                        {
                            AchievementTypeID = 6,
                            Category = "Goal",
                            Description = "Completed 3 savings goals.",
                            IconURL = "/images/badges/determined.png",
                            Name = "Determined",
                            Threshold = 3
                        },
                        new
                        {
                            AchievementTypeID = 7,
                            Category = "Goal",
                            Description = "Completed 5 savings goals.",
                            IconURL = "/images/badges/achiever.png",
                            Name = "Achiever",
                            Threshold = 5
                        },
                        new
                        {
                            AchievementTypeID = 8,
                            Category = "Goal",
                            Description = "Completed 10 savings goals!",
                            IconURL = "/images/badges/champion.png",
                            Name = "Champion",
                            Threshold = 10
                        },
                        new
                        {
                            AchievementTypeID = 9,
                            Category = "Expense",
                            Description = "Logged your first expense.",
                            IconURL = "/images/badges/first-purchase.png",
                            Name = "First Purchase",
                            Threshold = 1
                        },
                        new
                        {
                            AchievementTypeID = 10,
                            Category = "Expense",
                            Description = "Logged 20 expenses.",
                            IconURL = "/images/badges/expense-tracker.png",
                            Name = "Expense Tracker",
                            Threshold = 20
                        },
                        new
                        {
                            AchievementTypeID = 11,
                            Category = "Expense",
                            Description = "Logged 40 expenses.",
                            IconURL = "/images/badges/money-logger.png",
                            Name = "Money Logger",
                            Threshold = 40
                        },
                        new
                        {
                            AchievementTypeID = 12,
                            Category = "Expense",
                            Description = "Logged 100 expenses!",
                            IconURL = "/images/badges/financial-pro.png",
                            Name = "Financial Pro",
                            Threshold = 100
                        });
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Advice", b =>
                {
                    b.Property<int>("AdviceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdviceID"));

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GeneratedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SourceTrigger")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AdviceID");

                    b.HasIndex("ChildID", "IsRead")
                        .HasDatabaseName("IX_Advice_Child_IsRead");

                    b.ToTable("Advices");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Allowance", b =>
                {
                    b.Property<int>("AllowanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllowanceID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.Property<int?>("DailyHour")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GivenDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCreditedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MonthlyDay")
                        .HasColumnType("int");

                    b.Property<int>("ParentID")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SetDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WeeklyDay")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AllowanceID");

                    b.HasIndex("ParentID");

                    b.HasIndex("ChildID", "SetDate")
                        .HasDatabaseName("IX_Allowance_Child_SetDate");

                    b.ToTable("Allowances");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.AnalysisAdviceTemplate", b =>
                {
                    b.Property<int>("AdviceTemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdviceTemplateID"));

                    b.Property<string>("ActionSteps")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TriggerKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AdviceTemplateID");

                    b.ToTable("AnalysisAdviceTemplates");

                    b.HasData(
                        new
                        {
                            AdviceTemplateID = 1,
                            ActionSteps = "[\"Introduce a 24-hour waiting rule before any purchase over 20 EGP\",\"Talk to your child about how their mood affects their decisions\",\"Create a wish list to revisit purchases when they feel calmer\"]",
                            Description = "Your child spends a large portion of their money when in a specific emotional state, which may indicate mood-driven impulse purchases.",
                            Priority = 1,
                            Title = "Emotional Spending Alert",
                            TriggerKey = "HIGH_MOOD_SPENDING",
                            Type = "Alert"
                        },
                        new
                        {
                            AdviceTemplateID = 2,
                            ActionSteps = "[\"Set an automatic savings rule: put aside 20% of allowance immediately\",\"Use a visible savings goal to motivate consistent saving\",\"Discuss what they are saving toward to build purpose\"]",
                            Description = "Your child is saving very little of their allowance, spending most of it before the next payment cycle.",
                            Priority = 1,
                            Title = "Low Savings Rate",
                            TriggerKey = "LOW_SAVINGS_RATIO",
                            Type = "Alert"
                        },
                        new
                        {
                            AdviceTemplateID = 3,
                            ActionSteps = "[\"Help your child plan their spending at the start of each allowance cycle\",\"Set a weekly spending limit together\",\"Review purchases together at the end of each week\"]",
                            Description = "Your child is making purchases very frequently relative to their allowance cycle, which may lead to running out of money early.",
                            Priority = 2,
                            Title = "High Spending Frequency",
                            TriggerKey = "HIGH_SPENDING_FREQUENCY",
                            Type = "Alert"
                        },
                        new
                        {
                            AdviceTemplateID = 4,
                            ActionSteps = "[\"Encourage your child to explore other categories like books or school supplies\",\"Set a soft limit on spending in their dominant category per cycle\",\"Talk about balancing needs vs. wants\"]",
                            Description = "Your child is spending the majority of their money on a single category, showing limited variety in their purchasing decisions.",
                            Priority = 2,
                            Title = "Category Over-Focus",
                            TriggerKey = "IMPULSIVE_CATEGORY_FOCUS",
                            Type = "Alert"
                        },
                        new
                        {
                            AdviceTemplateID = 5,
                            ActionSteps = "[\"Sit together and pick one thing your child wants to save for\",\"Set a realistic target amount and timeline\",\"Check in on progress weekly to keep motivation high\"]",
                            Description = "Your child currently has no active savings goals, which removes a key motivation to save and plan ahead.",
                            Priority = 2,
                            Title = "No Active Savings Goals",
                            TriggerKey = "NO_ACTIVE_GOALS",
                            Type = "Alert"
                        },
                        new
                        {
                            AdviceTemplateID = 6,
                            ActionSteps = "[\"Discuss the concept of making money last through the full cycle\",\"Try splitting the allowance into spending and saving portions immediately\",\"Review what large purchases were made and whether they were planned\"]",
                            Description = "Your child's balance has dropped significantly since their last allowance, suggesting rapid spending after receiving money.",
                            Priority = 1,
                            Title = "Balance Draining Fast",
                            TriggerKey = "LOW_BALANCE_DRAIN",
                            Type = "Alert"
                        },
                        new
                        {
                            AdviceTemplateID = 7,
                            ActionSteps = "[\"Celebrate this achievement with non-monetary praise\",\"Help set a new, slightly more ambitious goal\",\"Share their success to reinforce the behavior\"]",
                            Description = "Your child has been completing savings goals consistently, showing strong financial discipline and follow-through.",
                            Priority = 1,
                            Title = "Goal Achiever",
                            TriggerKey = "GOAL_STREAK",
                            Type = "Strength"
                        },
                        new
                        {
                            AdviceTemplateID = 8,
                            ActionSteps = "[\"Praise their consistency to reinforce the habit\",\"Review logged expenses together to deepen their understanding\",\"Use the data to help them spot their own patterns\"]",
                            Description = "Your child has been logging their expenses regularly, building a strong habit of financial awareness.",
                            Priority = 2,
                            Title = "Consistent Tracker",
                            TriggerKey = "CONSISTENT_LOGGING",
                            Type = "Strength"
                        },
                        new
                        {
                            AdviceTemplateID = 9,
                            ActionSteps = "[\"Acknowledge this balance as a sign of developing impulse control\",\"Continue open conversations about how feelings relate to money decisions\",\"Encourage them to keep reflecting on their mood when spending\"]",
                            Description = "Your child's spending is distributed across different moods without any single emotional state dominating their purchases.",
                            Priority = 3,
                            Title = "Emotionally Balanced Spender",
                            TriggerKey = "BALANCED_MOOD_SPENDING",
                            Type = "Strength"
                        },
                        new
                        {
                            AdviceTemplateID = 10,
                            ActionSteps = "[\"Highlight how close they are to their goal to keep momentum\",\"Discuss what they will do once they reach it\",\"Suggest adding a stretch goal for extra motivation\"]",
                            Description = "Your child has made meaningful progress toward at least one savings goal, showing patience and planning ability.",
                            Priority = 2,
                            Title = "Steady Saver",
                            TriggerKey = "SAVING_PROGRESS",
                            Type = "Strength"
                        });
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Character", b =>
                {
                    b.Property<int>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterID"));

                    b.Property<string>("DefaultImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CharacterID");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Character_Name_Unique");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterID = 1,
                            DefaultImageUrl = "/images/characters/nova/profile.png",
                            Description = "Cool astronaut who loves street style and music",
                            Name = "Nova"
                        },
                        new
                        {
                            CharacterID = 2,
                            DefaultImageUrl = "/images/characters/cosmo/profile.png",
                            Description = "Ninja superhero astronaut always ready for action",
                            Name = "Cosmo"
                        },
                        new
                        {
                            CharacterID = 3,
                            DefaultImageUrl = "/images/characters/luna/profile.png",
                            Description = "Graceful ballerina astronaut in a pink skirt",
                            Name = "Luna"
                        },
                        new
                        {
                            CharacterID = 4,
                            DefaultImageUrl = "/images/characters/stella/profile.png",
                            Description = "Laid back astronaut in a hoodie who loves bubblegum",
                            Name = "Stella"
                        });
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.CharacterState", b =>
                {
                    b.Property<int>("StateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateID"));

                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ScreenContext")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StateID");

                    b.HasIndex("CharacterID", "ScreenContext")
                        .IsUnique()
                        .HasDatabaseName("IX_CharacterState_Character_Screen_Unique");

                    b.ToTable("CharacterStates");

                    b.HasData(
                        new
                        {
                            StateID = 6,
                            CharacterID = 1,
                            ImageUrl = "/images/characters/nova/expenses.png",
                            Message = "Let's see what you copped this week, astronaut.",
                            ScreenContext = "Expenses"
                        },
                        new
                        {
                            StateID = 7,
                            CharacterID = 2,
                            ImageUrl = "/images/characters/cosmo/expenses.png",
                            Message = "Time to investigate your spending like a true hero.",
                            ScreenContext = "Expenses"
                        },
                        new
                        {
                            StateID = 8,
                            CharacterID = 3,
                            ImageUrl = "/images/characters/luna/expenses.png",
                            Message = "Every purchase tells a story. Let's review yours.",
                            ScreenContext = "Expenses"
                        },
                        new
                        {
                            StateID = 9,
                            CharacterID = 4,
                            ImageUrl = "/images/characters/stella/expenses.png",
                            Message = "No stress, let's just vibe and see what you bought.",
                            ScreenContext = "Expenses"
                        },
                        new
                        {
                            StateID = 10,
                            CharacterID = 1,
                            ImageUrl = "/images/characters/nova/goals.png",
                            Message = "Your bank account looking real nice right now.",
                            ScreenContext = "Goals"
                        },
                        new
                        {
                            StateID = 11,
                            CharacterID = 2,
                            ImageUrl = "/images/characters/cosmo/goals.png",
                            Message = "Your savings power is charging up fast.",
                            ScreenContext = "Goals"
                        },
                        new
                        {
                            StateID = 12,
                            CharacterID = 3,
                            ImageUrl = "/images/characters/luna/goals.png",
                            Message = "Your savings are dancing beautifully toward your dreams.",
                            ScreenContext = "Goals"
                        },
                        new
                        {
                            StateID = 14,
                            CharacterID = 4,
                            ImageUrl = "/images/characters/stella/goals.png",
                            Message = "Pretty cool how your money's stacking up like that.",
                            ScreenContext = "Goals"
                        },
                        new
                        {
                            StateID = 15,
                            CharacterID = 1,
                            ImageUrl = "/images/characters/nova/profile.png",
                            Message = "Yo, what's good? Time to check those space credits.",
                            ScreenContext = "Profile"
                        },
                        new
                        {
                            StateID = 16,
                            CharacterID = 2,
                            ImageUrl = "/images/characters/cosmo/profile.png",
                            Message = "Looking strong, money warrior. Keep training.",
                            ScreenContext = "Profile"
                        },
                        new
                        {
                            StateID = 17,
                            CharacterID = 3,
                            ImageUrl = "/images/characters/luna/profile.png",
                            Message = "Welcome back, little star. Shall we begin?",
                            ScreenContext = "Profile"
                        },
                        new
                        {
                            StateID = 18,
                            CharacterID = 4,
                            ImageUrl = "/images/characters/stella/profile.png",
                            Message = "Hey there, space buddy. Just chilling and checking in.",
                            ScreenContext = "Profile"
                        },
                        new
                        {
                            StateID = 19,
                            CharacterID = 1,
                            ImageUrl = "/images/characters/nova/badges.png",
                            Message = "Another badge? You're on fire with this.",
                            ScreenContext = "Badges"
                        },
                        new
                        {
                            StateID = 20,
                            CharacterID = 2,
                            ImageUrl = "/images/characters/cosmo/badges.png",
                            Message = "Another victory unlocked. You're unstoppable.",
                            ScreenContext = "Badges"
                        },
                        new
                        {
                            StateID = 23,
                            CharacterID = 3,
                            ImageUrl = "/images/characters/luna/badges.png",
                            Message = "Each achievement is like a perfect spin.",
                            ScreenContext = "Badges"
                        },
                        new
                        {
                            StateID = 29,
                            CharacterID = 4,
                            ImageUrl = "/images/characters/stella/badges.png",
                            Message = "Nice, another one. You're doing your thing.",
                            ScreenContext = "Badges"
                        },
                        new
                        {
                            StateID = 32,
                            CharacterID = 1,
                            ImageUrl = "/images/characters/nova/quiz.png",
                            Message = "Aight, let's test that money brain of yours.",
                            ScreenContext = "Quiz"
                        },
                        new
                        {
                            StateID = 33,
                            CharacterID = 2,
                            ImageUrl = "/images/characters/cosmo/quiz.png",
                            Message = "Think fast, space cadet. Show me your skills.",
                            ScreenContext = "Quiz"
                        },
                        new
                        {
                            StateID = 34,
                            CharacterID = 3,
                            ImageUrl = "/images/characters/luna/quiz.png",
                            Message = "Let's gracefully glide through these questions together.",
                            ScreenContext = "Quiz"
                        },
                        new
                        {
                            StateID = 35,
                            CharacterID = 4,
                            ImageUrl = "/images/characters/stella/quiz.png",
                            Message = "Take it easy, no rush. You got this.",
                            ScreenContext = "Quiz"
                        });
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Child", b =>
                {
                    b.Property<int>("ChildID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChildID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal?>("BargainHunterScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CharacterID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("CurrentBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpenseCount")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("GoalCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("GoalOrientedPlannerScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ImpulsiveSpenderScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPersonalityFinalized")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastPersonalityUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("PrudentSaverScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuizCount")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TypeID")
                        .HasColumnType("int");

                    b.HasKey("ChildID");

                    b.HasIndex("CharacterID");

                    b.HasIndex("LoginCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Child_LoginCode_Unique");

                    b.HasIndex("TypeID");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.ChildAchievement", b =>
                {
                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.Property<int>("AchievementTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EarnedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("ChildID", "AchievementTypeID");

                    b.HasIndex("AchievementTypeID");

                    b.ToTable("ChildAchievements");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("MoneyAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MoodID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ExpenseID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("LogDate")
                        .HasDatabaseName("IX_Expense_LogDate");

                    b.HasIndex("MoodID");

                    b.HasIndex("ChildID", "LogDate")
                        .HasDatabaseName("IX_Expense_Child_LogDate");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.ExpenseCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryID");

                    b.ToTable("ExpenseCategories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Name = "Snacks / Food"
                        },
                        new
                        {
                            CategoryID = 2,
                            Name = "Games / Toys"
                        },
                        new
                        {
                            CategoryID = 3,
                            Name = "Gifts"
                        },
                        new
                        {
                            CategoryID = 4,
                            Name = "School Supplies"
                        },
                        new
                        {
                            CategoryID = 5,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.InitialProfilingQuestionnaire", b =>
                {
                    b.Property<int>("QuestionnaireID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionnaireID"));

                    b.Property<int?>("CalculatedTypeID")
                        .HasColumnType("int");

                    b.Property<int>("ChildAgeGroup")
                        .HasColumnType("int");

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FeelingAfterSpending")
                        .HasColumnType("int");

                    b.Property<int>("FeelingWhenSavingGrows")
                        .HasColumnType("int");

                    b.Property<int>("HasAllowance")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MoneyMindset")
                        .HasColumnType("int");

                    b.Property<int>("OutOfMoneyBehavior")
                        .HasColumnType("int");

                    b.Property<int>("ReactionTo100")
                        .HasColumnType("int");

                    b.Property<string>("SpendingCategories")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int>("SpendingPace")
                        .HasColumnType("int");

                    b.Property<int>("TriesToSave")
                        .HasColumnType("int");

                    b.HasKey("QuestionnaireID");

                    b.HasIndex("CalculatedTypeID");

                    b.HasIndex("ChildID")
                        .IsUnique()
                        .HasDatabaseName("IX_InitialProfiling_ChildID_Unique");

                    b.ToTable("InitialProfilingQuestionnaires");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Mood", b =>
                {
                    b.Property<int>("MoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoodID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MoodID");

                    b.ToTable("Moods");

                    b.HasData(
                        new
                        {
                            MoodID = 1,
                            Description = "Happy"
                        },
                        new
                        {
                            MoodID = 2,
                            Description = "Sad"
                        },
                        new
                        {
                            MoodID = 3,
                            Description = "Neutral"
                        },
                        new
                        {
                            MoodID = 4,
                            Description = "Excited"
                        },
                        new
                        {
                            MoodID = 5,
                            Description = "Regretful"
                        });
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<int?>("ChildID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NotificationID");

                    b.HasIndex("ChildID", "IsRead")
                        .HasDatabaseName("IX_Notification_Child_IsRead")
                        .HasFilter("[ChildID] IS NOT NULL");

                    b.HasIndex("ParentID", "IsRead")
                        .HasDatabaseName("IX_Notification_Parent_IsRead")
                        .HasFilter("[ParentID] IS NOT NULL");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Parent", b =>
                {
                    b.Property<int>("ParentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParentID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmailChangeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailChangeCodeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailConfirmationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailConfirmationCodeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPermanentlyDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetCodeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PermanentDeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("ParentID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Parent_Email_Unique");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.ParentChild", b =>
                {
                    b.Property<int>("ParentID")
                        .HasColumnType("int");

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.HasKey("ParentID", "ChildID");

                    b.HasIndex("ChildID");

                    b.ToTable("ParentChildren");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.PersonalityType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeID"));

                    b.Property<string>("ChildName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FunFacts")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StaticRecommendation")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Traits")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("TypeID");

                    b.ToTable("PersonalityTypes");

                    b.HasData(
                        new
                        {
                            TypeID = 1,
                            ChildName = "Money Explorer",
                            Desc = "We're still getting to know your child's financial personality. As they use the app and log expenses, we'll build a complete picture of their money habits and provide personalized guidance.",
                            FunFacts = "Every money expert started somewhere — you're just getting started!",
                            ParentName = "Pending Analysis",
                            StaticRecommendation = "[\"Keep encouraging your child to log their expenses regularly\", \"Guide your child to try saving for a specific goal\", \"Have your child complete the story quizzes to help us better understand their money personality\"]",
                            Traits = "[\"Discovering spending patterns\", \"Building financial profile\", \"Learning money habits\"]"
                        },
                        new
                        {
                            TypeID = 2,
                            ChildName = "Speedy Spender",
                            Desc = "Quick purchases driven by excitement, low savings ratios.",
                            FunFacts = "Did you know? Speedy Spenders are super fun and spontaneous — the trick is to pause for just one day before buying!",
                            ParentName = "Impulsive Spender",
                            StaticRecommendation = "[\"Encourage a 24-hour waiting rule before they make non-essential purchases.\", \"Introduce a visual savings jar or progress bar so they can see their money build up.\", \"Work together to create a simple shopping list before visiting stores or online apps.\", \"Suggest setting aside a flat 20% of their allowance instantly into savings before spending any.\"]",
                            Traits = "[\"Buys quickly\",\"Gets excited about new things\",\"Struggles to save\"]"
                        },
                        new
                        {
                            TypeID = 3,
                            ChildName = "Treasure Keeper",
                            Desc = "High savings ratios and deliberate spending decisions.",
                            FunFacts = "Did you know? Treasure Keepers are rare — only the wisest kids know how to grow their coins into something amazing!",
                            ParentName = "Prudent Saver",
                            StaticRecommendation = "[\"Help them set exciting, long-term savings goals so they don't hold onto money out of fear.\", \"Give them permission to enjoy some 'fun spending' to avoid eventual saving burnout.\", \"Introduce basic age-appropriate concepts of investing or earning interest on accumulated funds.\"]",
                            Traits = "[\"Thinks before buying\",\"Saves consistently\",\"Rarely regrets purchases\"]"
                        },
                        new
                        {
                            TypeID = 4,
                            ChildName = "Dream Builder",
                            Desc = "Balanced approach to spending and saving, with steady goal contributions. Plans purchases carefully.",
                            FunFacts = "Did you know? Dream Builders are natural achievers — every coin you save is one step closer to your dream!",
                            ParentName = "Goal-Oriented Planner",
                            StaticRecommendation = "[\"Help them break down very large, daunting savings goals into smaller, reachable milestones.\", \"Celebrate or match their savings when they cross a major milestone to reward consistency.\", \"Keep their targeted goals visually prominent in conversation to sustain their natural planning habits.\"]",
                            Traits = "[\"Creates clear savings goals\", \"Balances fun spending with saving\", \"Tracks progress regularly\", \"Plans purchases in advance\", \"Stays motivated by dreams\"]"
                        },
                        new
                        {
                            TypeID = 5,
                            ChildName = "Deal Detective",
                            Desc = "Emphasizes value and deals, strategic spending. Loves finding the best prices and getting good value.",
                            FunFacts = "Did you know? Deal Detectives have a superpower — they can spot a great deal from a mile away!",
                            ParentName = "Bargain Hunter",
                            StaticRecommendation = "[\"Remind them to make a strict shopping list so they don't buy things simply because they are 'on sale'.\", \"Challenge them to find coupon codes or comparison shop to engage their detective strengths productively.\", \"Teach them about quality vs. price so they understand that cheap doesn't always mean high value.\"]",
                            Traits = "[\"Compares prices before buying\", \"Loves finding good deals\", \"Waits for sales\", \"Values getting the most for money\", \"Shares deals with others\"]"
                        });
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.QuizAnswer", b =>
                {
                    b.Property<int>("AnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerID"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FeedbackMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PersonalityTypeID")
                        .HasColumnType("int");

                    b.Property<int>("StoryID")
                        .HasColumnType("int");

                    b.HasKey("AnswerID");

                    b.HasIndex("PersonalityTypeID");

                    b.HasIndex("StoryID");

                    b.ToTable("QuizAnswers");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.QuizLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<int>("AnswerID")
                        .HasColumnType("int");

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("PersonalityTypeTypeID")
                        .HasColumnType("int");

                    b.Property<int>("StoryID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("AnswerID");

                    b.HasIndex("PersonalityTypeTypeID");

                    b.HasIndex("StoryID");

                    b.HasIndex("ChildID", "CompletedDate")
                        .HasDatabaseName("IX_QuizLog_Child_CompletedDate");

                    b.HasIndex("ChildID", "StoryID")
                        .IsUnique()
                        .HasDatabaseName("IX_QuizLog_Child_Story_Unique");

                    b.ToTable("QuizLogs");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.SavingsGoal", b =>
                {
                    b.Property<int>("GoalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoalID"));

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsChallenge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<decimal?>("RewardValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("GoalID");

                    b.HasIndex("ParentID");

                    b.HasIndex("ChildID", "Status")
                        .HasDatabaseName("IX_SavingsGoal_Child_Status");

                    b.ToTable("SavingsGoals");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.StoryQuizTemplate", b =>
                {
                    b.Property<int>("StoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoryID"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TargetAgeMax")
                        .HasColumnType("int");

                    b.Property<int>("TargetAgeMin")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("StoryID");

                    b.HasIndex("TargetAgeMin", "TargetAgeMax")
                        .HasDatabaseName("IX_StoryQuiz_AgeRange");

                    b.ToTable("StoryQuizTemplates");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<int?>("AllowanceID")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransactionID");

                    b.HasIndex("AllowanceID");

                    b.HasIndex("ParentID");

                    b.HasIndex("ChildID", "TransactionDate")
                        .HasDatabaseName("IX_Transaction_Child_TransactionDate");

                    b.HasIndex("Type", "TransactionDate")
                        .HasDatabaseName("IX_Transaction_Type_TransactionDate");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Advice", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("Advices")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Allowance", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("Allowances")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.Parent", "Parent")
                        .WithMany("Allowances")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.CharacterState", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.Character", "Character")
                        .WithMany("CharacterStates")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Child", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.Character", "SelectedCharacter")
                        .WithMany("Children")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MoneyMirror.Core.Models.PersonalityType", "PersonalityType")
                        .WithMany("Children")
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PersonalityType");

                    b.Navigation("SelectedCharacter");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.ChildAchievement", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.AchievementType", "AchievementType")
                        .WithMany("ChildAchievements")
                        .HasForeignKey("AchievementTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("ChildAchievements")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AchievementType");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Expense", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.ExpenseCategory", "ExpenseCategory")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("Expenses")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.Mood", "Mood")
                        .WithMany("Expenses")
                        .HasForeignKey("MoodID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("ExpenseCategory");

                    b.Navigation("Mood");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.InitialProfilingQuestionnaire", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.PersonalityType", "CalculatedPersonalityType")
                        .WithMany()
                        .HasForeignKey("CalculatedTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithOne("InitialProfilingQuestionnaire")
                        .HasForeignKey("MoneyMirror.Core.Models.InitialProfilingQuestionnaire", "ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalculatedPersonalityType");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Notification", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("Notifications")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoneyMirror.Core.Models.Parent", "Parent")
                        .WithMany("Notifications")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.ParentChild", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("ParentChildren")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.Parent", "Parent")
                        .WithMany("ParentChildren")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.QuizAnswer", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.PersonalityType", "PersonalityType")
                        .WithMany()
                        .HasForeignKey("PersonalityTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.StoryQuizTemplate", "StoryQuizTemplate")
                        .WithMany("Answers")
                        .HasForeignKey("StoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalityType");

                    b.Navigation("StoryQuizTemplate");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.QuizLog", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.QuizAnswer", "QuizAnswer")
                        .WithMany("QuizLogs")
                        .HasForeignKey("AnswerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("QuizLogs")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.PersonalityType", null)
                        .WithMany("QuizLogs")
                        .HasForeignKey("PersonalityTypeTypeID");

                    b.HasOne("MoneyMirror.Core.Models.StoryQuizTemplate", "StoryQuizTemplate")
                        .WithMany("QuizLogs")
                        .HasForeignKey("StoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("QuizAnswer");

                    b.Navigation("StoryQuizTemplate");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.SavingsGoal", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("SavingsGoals")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.Parent", "Parent")
                        .WithMany("ChallengeGoals")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Transaction", b =>
                {
                    b.HasOne("MoneyMirror.Core.Models.Allowance", "Allowance")
                        .WithMany("Transactions")
                        .HasForeignKey("AllowanceID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MoneyMirror.Core.Models.Child", "Child")
                        .WithMany("Transactions")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MoneyMirror.Core.Models.Parent", "Parent")
                        .WithMany("InitiatedTransactions")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Allowance");

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.AchievementType", b =>
                {
                    b.Navigation("ChildAchievements");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Allowance", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Character", b =>
                {
                    b.Navigation("CharacterStates");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Child", b =>
                {
                    b.Navigation("Advices");

                    b.Navigation("Allowances");

                    b.Navigation("ChildAchievements");

                    b.Navigation("Expenses");

                    b.Navigation("InitialProfilingQuestionnaire");

                    b.Navigation("Notifications");

                    b.Navigation("ParentChildren");

                    b.Navigation("QuizLogs");

                    b.Navigation("SavingsGoals");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Mood", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.Parent", b =>
                {
                    b.Navigation("Allowances");

                    b.Navigation("ChallengeGoals");

                    b.Navigation("InitiatedTransactions");

                    b.Navigation("Notifications");

                    b.Navigation("ParentChildren");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.PersonalityType", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("QuizLogs");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.QuizAnswer", b =>
                {
                    b.Navigation("QuizLogs");
                });

            modelBuilder.Entity("MoneyMirror.Core.Models.StoryQuizTemplate", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("QuizLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
